"""Version 2 YouTube integration

Revision ID: 2b30e71f3160
Revises: 
Create Date: 2026-06-03 16:11:54.296076

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b30e71f3160'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment_results', schema=None) as batch_op:
        batch_op.add_column(sa.Column('published_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('youtube_analyses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('video_description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('published_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('view_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('like_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('comment_limit', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('api_error', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('youtube_analyses', schema=None) as batch_op:
        batch_op.drop_column('api_error')
        batch_op.drop_column('comment_limit')
        batch_op.drop_column('like_count')
        batch_op.drop_column('view_count')
        batch_op.drop_column('published_at')
        batch_op.drop_column('video_description')

    with op.batch_alter_table('comment_results', schema=None) as batch_op:
        batch_op.drop_column('published_at')

    # ### end Alembic commands ###
