"""Version 4 AI engine upgrade

Revision ID: fbded892f0a3
Revises: 2b30e71f3160
Create Date: 2026-06-05 12:53:06.406879

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fbded892f0a3'
down_revision = '2b30e71f3160'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('analyses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('average_sentiment', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('average_toxicity', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('average_spam', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('average_bot_score', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('critical_comments_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('analysis_summary', sa.Text(), nullable=True))

    with op.batch_alter_table('comment_results', schema=None) as batch_op:
        batch_op.add_column(sa.Column('spam_confidence', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('toxicity_confidence', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('sentiment_confidence', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('bot_confidence', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('recommendation', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment_results', schema=None) as batch_op:
        batch_op.drop_column('recommendation')
        batch_op.drop_column('bot_confidence')
        batch_op.drop_column('sentiment_confidence')
        batch_op.drop_column('toxicity_confidence')
        batch_op.drop_column('spam_confidence')

    with op.batch_alter_table('analyses', schema=None) as batch_op:
        batch_op.drop_column('analysis_summary')
        batch_op.drop_column('critical_comments_count')
        batch_op.drop_column('average_bot_score')
        batch_op.drop_column('average_spam')
        batch_op.drop_column('average_toxicity')
        batch_op.drop_column('average_sentiment')

    # ### end Alembic commands ###
